//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Eunji/Input/InputActionTower.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionTower : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionTower()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionTower"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""52063d96-c0d7-4c2c-8bd3-dd184e6c6c94"",
            ""actions"": [
                {
                    ""name"": ""TouchMenu"",
                    ""type"": ""Button"",
                    ""id"": ""6cb5f0b5-bed4-4f4d-9afe-32cc96bd7b05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""800dc238-95b7-442d-91d5-62759b0a436f"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Touch"",
                    ""action"": ""TouchMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3e0a45e-27f8-427f-b9a7-8c7e1baf8579"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse&Touch"",
                    ""action"": ""TouchMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse&Touch"",
            ""bindingGroup"": ""Mouse&Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_TouchMenu = m_Touch.FindAction("TouchMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private ITouchActions m_TouchActionsCallbackInterface;
    private readonly InputAction m_Touch_TouchMenu;
    public struct TouchActions
    {
        private @InputActionTower m_Wrapper;
        public TouchActions(@InputActionTower wrapper) { m_Wrapper = wrapper; }
        public InputAction @TouchMenu => m_Wrapper.m_Touch_TouchMenu;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void SetCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterface != null)
            {
                @TouchMenu.started -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchMenu;
                @TouchMenu.performed -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchMenu;
                @TouchMenu.canceled -= m_Wrapper.m_TouchActionsCallbackInterface.OnTouchMenu;
            }
            m_Wrapper.m_TouchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TouchMenu.started += instance.OnTouchMenu;
                @TouchMenu.performed += instance.OnTouchMenu;
                @TouchMenu.canceled += instance.OnTouchMenu;
            }
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    private int m_MouseTouchSchemeIndex = -1;
    public InputControlScheme MouseTouchScheme
    {
        get
        {
            if (m_MouseTouchSchemeIndex == -1) m_MouseTouchSchemeIndex = asset.FindControlSchemeIndex("Mouse&Touch");
            return asset.controlSchemes[m_MouseTouchSchemeIndex];
        }
    }
    public interface ITouchActions
    {
        void OnTouchMenu(InputAction.CallbackContext context);
    }
}
